"""empty message

Revision ID: 2943432c46f1
Revises: d6f01617ae07
Create Date: 2023-02-23 21:57:05.183168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2943432c46f1'
down_revision = 'd6f01617ae07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('left_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('left_bar')
    # ### end Alembic commands ###
