"""empty message

Revision ID: 51c6667df93a
Revises: c02b09de1176
Create Date: 2023-02-25 06:08:46.113097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c6667df93a'
down_revision = 'c02b09de1176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_text_first', sa.Text(), nullable=True),
    sa.Column('line_text_last', sa.Text(), nullable=True),
    sa.Column('volume_image', sa.String(length=150), nullable=True),
    sa.Column('volume_name', sa.String(length=300), nullable=True),
    sa.Column('issues_in_prog', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_data')
    # ### end Alembic commands ###
