"""empty message

Revision ID: c02b09de1176
Revises: 2943432c46f1
Create Date: 2023-02-24 18:38:04.019076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02b09de1176'
down_revision = '2943432c46f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=True),
    sa.Column('image_2', sa.String(length=150), nullable=True),
    sa.Column('text_1', sa.String(length=300), nullable=True),
    sa.Column('text_2', sa.String(length=300), nullable=True),
    sa.Column('text_3', sa.String(length=300), nullable=True),
    sa.Column('text_4', sa.String(length=300), nullable=True),
    sa.Column('text_5', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('right_bar')
    # ### end Alembic commands ###
