"""empty message

Revision ID: d6f01617ae07
Revises: 
Create Date: 2022-04-20 16:29:01.434305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f01617ae07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('psw', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leftmenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('photographed', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('left_menu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_menu'], ['leftmenu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jurnals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('authors_sup', sa.String(length=1000), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('doi_text', sa.String(length=1000), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('Views', sa.Integer(), nullable=True),
    sa.Column('sub_text', sa.Text(), nullable=True),
    sa.Column('author_email', sa.String(length=200), nullable=True),
    sa.Column('received_date', sa.String(length=200), nullable=True),
    sa.Column('accepted_date', sa.String(length=200), nullable=True),
    sa.Column('valid_articles', sa.Boolean(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurnals')
    op.drop_table('categories')
    op.drop_table('leftmenu')
    op.drop_table('admins')
    # ### end Alembic commands ###
