"""empty message

Revision ID: eac53ef86530
Revises: b026a3188340
Create Date: 2023-09-28 00:04:25.841883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac53ef86530'
down_revision = 'b026a3188340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_board_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editorial_board_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['editorial_board_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editorial_board_items')
    op.drop_table('editorial_board_titles')
    # ### end Alembic commands ###
